# Project information
site_name: 쿠브네티스 스쿨
site_url: https://cloudacode.com/hello-kubernetes/
site_author: kcfigaro@gmail.com, juner84s@gmail.com, steven.hj.shim@gmail.com
site_description: >-
  Introduces the process of building various applications in the cloud environment
  and improving development procedures with DevOps culture.

# Repository
repo_name: cloudacode/hello-kubernetes
repo_url: https://github.com/cloudacode/hello-kubernetes
edit_uri: ""

# Google Analytics
extra:
  analytics:
    provider: google
    property: G-L86XX3YR79

# Configuration
theme:
  name: material
  custom_dir: overrides
  logo: assets/application-brackets-outline.png
  favicon: assets/application-brackets-black.png
  palette:
    - scheme: default
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/weather-night
        name: Switch to light mode

markdown_extensions:
  - admonition
  - pymdownx.highlight
  - tables
  - meta

# Page tree
nav:
  - Home: index.md
  - 1. Get started:
    - hello-kubernetes/section01/what-is-container.md
    - hello-kubernetes/section01/what-is-kubernetes.md
    - hello-kubernetes/section01/what-is-helm.md
    - 핸즈온 실습:
      - hello-kubernetes/section01/handson/setup-local-k8s-kind.md
      - hello-kubernetes/section01/handson/setup-cloud-k8s-eks.md
      - hello-kubernetes/section01/handson/setup-redis-via-helm.md
  - 2. Fundamentals:
    - hello-kubernetes/section02/pod-namespce.md
    - hello-kubernetes/section02/pod-requests-limits.md
    - hello-kubernetes/section02/service-ingress.md
    - hello-kubernetes/section02/deployment-replicaset.md
    - hello-kubernetes/section02/readiness-liveness-probe.md
    - hello-kubernetes/section02/configmaps-secrets.md
    - 핸즈온 실습:
      - hello-kubernetes/section02/handson/s2-h1.md
      - hello-kubernetes/section02/handson/s2-h2.md
      - hello-kubernetes/section02/handson/resource-qos.md
      - hello-kubernetes/section02/handson/service-ingress.md
      - hello-kubernetes/section02/handson/configmaps-secrets.md
  - 3. Advanced:
    - hello-kubernetes/section03/horizontal-pod-autoscaling.md
    - hello-kubernetes/section03/storage-persistent-volume.md
    - hello-kubernetes/section03/statefulset.md
    - hello-kubernetes/section03/s3-c4.md
    - hello-kubernetes/section03/s3-c5.md
    - hello-kubernetes/section03/pod-resource-advanced.md
    - 핸즈온 실습:
      - hello-kubernetes/section03/handson/horizontal-pod-autoscaling.md
      - hello-kubernetes/section03/handson/storage-persistent-volume.md
      - hello-kubernetes/section03/handson/statefulset.md
  - 4. Production:
      - hello-kubernetes/section04/k8-essential-components.md
      - hello-kubernetes/section04/ingress-nginx.md
      - Cloud Provider:
        - hello-kubernetes/section04/s4-c1.md
        - hello-kubernetes/section04/s4-c2.md
      - Mgmt Service:
        - hello-kubernetes/section04/keda-hpa.md
        - hello-kubernetes/section04/s4-c4.md
  - 기타 자료:
    - Blog ⧉: https://medium.com/@cloudacode
    - Youtube ⧉: https://www.youtube.com/channel/UCw46J_QQ3-HrjPsSsuOSDdQ
