# Project information
site_name: 쿠브네티스 스쿨
site_url: https://cloudacode.com/hello-kubernetes/
site_author: KC Chang

# Repository
repo_name: cloudacode/hello-kubernetes
repo_url: https://github.com/cloudacode/hello-kubernetes
edit_uri: ""

# Google Analytics
extra:
  analytics:
    provider: google
    property: G-L86XX3YR79

# Configuration
theme:
  name: material
  logo: assets/application-brackets-outline.png
  favicon: assets/application-brackets-black.png
  palette:
    - scheme: default
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/weather-night
        name: Switch to light mode

markdown_extensions:
  - admonition
  - pymdownx.highlight

# Page tree
nav:
  - Home: index.md
  - 1. Get started:
    - hello-kubernetes/section01/what-is-container.md
    - hello-kubernetes/section01/s1-c2.md
    - hello-kubernetes/section01/s1-c3.md
    - hello-kubernetes/section01/s1-h1.md
  - 2. Fundamentals:
    - hello-kubernetes/section02/s2-c1.md
    - hello-kubernetes/section02/s2-c2.md
    - hello-kubernetes/section02/s2-c3.md
    - hello-kubernetes/section02/s2-c4.md
    - hello-kubernetes/section02/s2-c5.md
    - hello-kubernetes/section02/s2-h1.md
  - 3. Advanced:
      - hello-kubernetes/section03/s3-c1.md
      - hello-kubernetes/section03/s3-c2.md
      - hello-kubernetes/section03/s3-c3.md
  - 4. Production:
      - hello-kubernetes/section04/k8-essential-components.md
      - Cloud Provider: 
        - hello-kubernetes/section04/s4-c1.md
        - hello-kubernetes/section04/s4-c2.md
      - Mgmt Service:
        - hello-kubernetes/section04/s4-c3.md
        - hello-kubernetes/section04/s4-c4.md
  - 기타 자료:
    - Blog ⧉: https://medium.com/@cloudacode
    - Youtube ⧉: https://www.youtube.com/channel/UCw46J_QQ3-HrjPsSsuOSDdQ
