apiVersion: v1
kind: Pod
metadata:
  name: busybox-sleep-1000
spec:
  containers:
  - name: busybox
    image: busybox:1.28
    args:
    - sleep
    - "1000"
    volumeMounts:
    - mountPath: /data
      name: empty-data
  volumes:
  - name: empty-data
    emptyDir: {}
